[package]
name = "ggrs-no-rapier"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
bevy_ggrs = { version = "0.17.0", features = ["wasm-bindgen"] }
bevy_matchbox = { version = "0.11.0", features = ["ggrs"] }
bevy_utils = "0.15.3"

[profile.dev.package."*"]
opt-level = 2
